#str(subSetData)
sub_hpc$subMetering1 <- as.numeric(sub_hpc$Sub_metering_1)
sub_hpc$subMetering2 <- as.numeric(sub_hpc$Sub_metering_2)
sub_hpc$subMetering3 <- as.numeric(sub_hpc$Sub_metering_3)

png("plot3.png", width=480, height=480)
plot(sub_hpc$dt, sub_hpc$subMetering1, type="l", ylab="Energy sub metering", xlab="")
lines(sub_hpc$dt, sub_hpc$subMetering2, type="l", col="red")
lines(sub_hpc$dt, sub_hpc$subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.0, col=c("black", "red", "blue"))
dev.off()